"""The synthetic "human demonstration" for Stage 1 -- no video involved.

Two modes, per the Stage-1 spec:

(a) :func:`scripted_reference` -- a scripted min-jerk ramp to the goal angle
    (same formula ``scripts/generate_source_demo.py`` uses for the original
    Physics-OT pipeline's scripted source trajectory; duplicated locally
    rather than imported across an unpackaged script -- see
    :func:`min_jerk_theta`'s docstring below).
(b) :func:`integrated_reference` -- forward-integrate Eq 15 itself with a
    scripted torque profile. Because the reference is generated by exactly
    the same dynamics ``knob_env.py`` uses, this is what makes a
    D_POISE(rho*, rho*) ~= 0 self-distance check meaningful (Stage 1's
    "Cost sanity" check): reference and rollout aren't just similar, their
    generating dynamics are identical by construction.

Both modes hand raw ``(t, theta)`` samples to ``physics_ot.references.
build_reference`` (reused unchanged -- spline-smooth, differentiate
analytically, resample to T_H tokens, compute tau* via ``KnobDynamics.
required_generalized_force``) and then to ``token_builder.build_token`` to
produce the actual 5-channel reference Token.
"""

from __future__ import annotations

from typing import Callable

import numpy as np
import torch

from physics_ot.dynamics.knob import KnobDynamics, KnobParams
from physics_ot.references.build_reference import PhysicsReference, build_reference

from .token_builder import Token, build_token


def min_jerk_theta(t: np.ndarray, theta0: float, theta_goal: float, reach_duration: float) -> np.ndarray:
    """Deliberately duplicated, not imported, from ``scripts.generate_source_demo``:
    ``scripts/`` is a loose collection of entry points (no ``__init__.py``,
    not declared in ``pyproject.toml``'s package list), so importing across
    it is fragile (depends on cwd/sys.path rather than an installed
    package). This is a stable 3-line closed-form formula with no
    maintenance burden, so a documented duplicate is safer than a fragile
    cross-script import or touching the already remote-validated original.
    """
    tau = np.clip(t / reach_duration, 0.0, 1.0)
    return theta0 + (theta_goal - theta0) * (10 * tau**3 - 15 * tau**4 + 6 * tau**5)


def _finalize_reference(
    t_raw: np.ndarray,
    theta_raw: np.ndarray,
    params: KnobParams,
    theta_goal: float,
    num_tokens: int,
    smoothing: float,
    impulse_window: int,
) -> tuple[PhysicsReference, Token]:
    ref = build_reference(t_raw, theta_raw, params, theta_goal, num_tokens=num_tokens, smoothing=smoothing)
    dt = float(ref.time[1] - ref.time[0]) if ref.time.shape[0] > 1 else 1.0

    progress = torch.from_numpy(ref.progress.astype(np.float32))
    theta_dot = torch.from_numpy(ref.velocity.astype(np.float32))
    tau = torch.from_numpy(ref.wrench.astype(np.float32))  # tau* -- Eq target_torque, already computed by build_reference

    token = build_token(progress, theta_dot, tau, params, dt, window_h=impulse_window)
    return ref, token


def scripted_reference(
    params: KnobParams,
    theta_goal: float,
    reach_duration: float = 2.0,
    total_duration: float = 6.0,
    sample_rate: float = 30.0,
    num_tokens: int = 64,
    smoothing: float = 0.0,
    impulse_window: int = 5,
) -> tuple[PhysicsReference, Token]:
    """(a) A scripted min-jerk ramp theta0 -> theta_goal, holding at theta_goal
    for the remainder of ``total_duration`` (mirrors ``generate_source_demo.
    py``'s existing behavior for the original Physics-OT pipeline)."""
    t = np.arange(0.0, total_duration + 1e-9, 1.0 / sample_rate)
    theta = min_jerk_theta(t, params.theta0, theta_goal, reach_duration)
    return _finalize_reference(t, theta, params, theta_goal, num_tokens, smoothing, impulse_window)


def constant_ramp_torque(magnitude: float = 0.08, ramp_time: float = 1.0) -> Callable[[torch.Tensor], torch.Tensor]:
    """A smooth tanh-ramped constant-torque profile for :func:`integrated_reference`."""

    def profile(t: torch.Tensor) -> torch.Tensor:
        return magnitude * torch.tanh(t / max(ramp_time, 1e-6))

    return profile


def integrated_reference(
    params: KnobParams,
    theta_goal: float,
    torque_fn: Callable[[torch.Tensor], torch.Tensor] | None = None,
    total_duration: float = 6.0,
    physics_dt: float = 1.0 / 120.0,
    num_tokens: int = 64,
    smoothing: float = 0.0,
    impulse_window: int = 5,
) -> tuple[PhysicsReference, Token]:
    """(b) Forward-integrate Eq 15 with a scripted torque profile using
    semi-implicit Euler -- the same integration scheme ``knob_env.py`` uses,
    so reference and rollout dynamics are generated identically."""
    torque_fn = torque_fn or constant_ramp_torque()
    dynamics = KnobDynamics(params)

    n_steps = int(round(total_duration / physics_dt)) + 1
    t = torch.linspace(0.0, total_duration, n_steps)
    theta = torch.zeros(n_steps)
    theta_dot = torch.zeros(n_steps)
    theta[0] = params.theta0

    for i in range(1, n_steps):
        tau_i = torque_fn(t[i - 1])
        theta_ddot = (tau_i + dynamics.passive_torque(theta[i - 1], theta_dot[i - 1])) / params.inertia
        theta_dot[i] = theta_dot[i - 1] + theta_ddot * physics_dt
        theta[i] = theta[i - 1] + theta_dot[i] * physics_dt

    return _finalize_reference(
        t.numpy(), theta.numpy(), params, theta_goal, num_tokens, smoothing, impulse_window
    )
